// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4GTe16OPaNti9mQArGp3-jpF_RgNuaU',
    appId: '1:757218516360:web:4c44adc7d46702a9c6ae3d',
    messagingSenderId: '757218516360',
    projectId: 'thasbeeh-counter',
    authDomain: 'thasbeeh-counter.firebaseapp.com',
    databaseURL: 'https://thasbeeh-counter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thasbeeh-counter.firebasestorage.app',
    measurementId: 'G-V6NNW7E8RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOYgsU3mPTyIMIMb2lKjlCg-Qike9P87k',
    appId: '1:757218516360:android:148676c818240fc6c6ae3d',
    messagingSenderId: '757218516360',
    projectId: 'thasbeeh-counter',
    databaseURL: 'https://thasbeeh-counter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thasbeeh-counter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHS1WQThAWi-y41kpKXiAxX_lmhUodyFQ',
    appId: '1:757218516360:ios:b94948b91567b6bbc6ae3d',
    messagingSenderId: '757218516360',
    projectId: 'thasbeeh-counter',
    databaseURL: 'https://thasbeeh-counter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thasbeeh-counter.firebasestorage.app',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHS1WQThAWi-y41kpKXiAxX_lmhUodyFQ',
    appId: '1:757218516360:ios:b94948b91567b6bbc6ae3d',
    messagingSenderId: '757218516360',
    projectId: 'thasbeeh-counter',
    databaseURL: 'https://thasbeeh-counter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thasbeeh-counter.firebasestorage.app',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX4GTe16OPaNti9mQArGp3-jpF_RgNuaU',
    appId: '1:757218516360:web:7834390351263dc4c6ae3d',
    messagingSenderId: '757218516360',
    projectId: 'thasbeeh-counter',
    authDomain: 'thasbeeh-counter.firebaseapp.com',
    databaseURL: 'https://thasbeeh-counter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thasbeeh-counter.firebasestorage.app',
    measurementId: 'G-M8Q7GCL0XF',
  );
}
